// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type PublishedVideos struct {
	ID          uuid.UUID `json:"id"`
	VideoID     uuid.UUID `json:"video_id"`
	PublishedBy uuid.UUID `json:"published_by"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Users struct {
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	Email           string       `json:"email"`
	Contact         string       `json:"contact"`
	Password        string       `json:"password"`
	UserType        string       `json:"user_type"`
	IsAccountActive sql.NullBool `json:"is_account_active"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

type VerifyVideos struct {
	ID        uuid.UUID `json:"id"`
	VideoID   uuid.UUID `json:"video_id"`
	VerifyBy  uuid.UUID `json:"verify_by"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type VideoByAdmin struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	FileAddress string    `json:"file_address"`
	UploadedBy  uuid.UUID `json:"uploaded_by"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type VideoVerificationProcessFailed struct {
	Id                   uuid.UUID     `json:"Id"`
	VideoID              uuid.UUID     `json:"video_id"`
	VerificationFailedBy uuid.NullUUID `json:"verification_failed_by"`
	UnpublishedBy        uuid.NullUUID `json:"unpublished_by"`
	Status               string        `json:"status"`
	Reason               string        `json:"reason"`
	IsVerificationFailed sql.NullBool  `json:"is_verification_failed"`
	IsUnpublished        sql.NullBool  `json:"is_unpublished"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}
