// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: published_videos.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPublishedVideo = `-- name: CreatePublishedVideo :one
insert into published_videos (
    video_id,
    published_by,
    status
) values (
    $1,$2,$3
) returning id, video_id, published_by, status, created_at, updated_at
`

type CreatePublishedVideoParams struct {
	VideoID     uuid.UUID `json:"video_id"`
	PublishedBy uuid.UUID `json:"published_by"`
	Status      string    `json:"status"`
}

func (q *Queries) CreatePublishedVideo(ctx context.Context, arg CreatePublishedVideoParams) (PublishedVideos, error) {
	row := q.db.QueryRowContext(ctx, createPublishedVideo, arg.VideoID, arg.PublishedBy, arg.Status)
	var i PublishedVideos
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.PublishedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
