// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: video_by_admin.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getVideoByAdmin = `-- name: GetVideoByAdmin :many
select id, title, file_address, uploaded_by, status, created_at, updated_at from video_by_admin
where uploaded_by = $1 and status= $2
order by created_at desc
limit $3
offset $4
`

type GetVideoByAdminParams struct {
	UploadedBy uuid.UUID `json:"uploaded_by"`
	Status     string    `json:"status"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) GetVideoByAdmin(ctx context.Context, arg GetVideoByAdminParams) ([]VideoByAdmin, error) {
	rows, err := q.db.QueryContext(ctx, getVideoByAdmin,
		arg.UploadedBy,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoByAdmin{}
	for rows.Next() {
		var i VideoByAdmin
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FileAddress,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoStatus = `-- name: UpdateVideoStatus :execresult
update video_by_admin
set status = $2
where id = $1
`

type UpdateVideoStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVideoStatus, arg.ID, arg.Status)
}

const uploadVideoByAdmin = `-- name: UploadVideoByAdmin :one
insert into video_by_admin (
    title,
    file_address,
    uploaded_by,
    status
) values (
    $1,$2,$3,$4
) returning id, title, file_address, uploaded_by, status, created_at, updated_at
`

type UploadVideoByAdminParams struct {
	Title       string    `json:"title"`
	FileAddress string    `json:"file_address"`
	UploadedBy  uuid.UUID `json:"uploaded_by"`
	Status      string    `json:"status"`
}

func (q *Queries) UploadVideoByAdmin(ctx context.Context, arg UploadVideoByAdminParams) (VideoByAdmin, error) {
	row := q.db.QueryRowContext(ctx, uploadVideoByAdmin,
		arg.Title,
		arg.FileAddress,
		arg.UploadedBy,
		arg.Status,
	)
	var i VideoByAdmin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FileAddress,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
